[tool.poetry]
name = "mojap-arrow-pd-parser"
version = "0.0.1"
description = "mojap-arrow-pd-parser"
authors = ["Karik Isichei <karik.isichei@digital.justice.gov.uk>",
           "Alec Johnson <alec.johnson@digital.justice.gov.uk>",
           "Kimberley Brett <kimberley.brett@digital.justice.gov.uk>,
           "Thomas Hirsch <thomas.hirsch@digital.justice.gov.uk>",
           "Jacob Browning <jacob.browning@digital.justice.gov.uk>,
           "Jacob Hamblin-Pyke <jacob.hamblin-pyke@digital.justice.gov.uk>,
           "George Kelly <george.kelly@digital.justice.gov.uk>",
           ]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<3.9"
dataengineeringutils3 = "^1.0.1"
frictionless = "^3.23.3"
boto3 = "^1.14.7"
jsonschema = "^3.2.0"
pyyaml = "^5.3.1"
iam_builder = "^3.7.0"
importlib-metadata = "^1.7"
pandas = { version = "1.1.3", optional = true }
great-expectations = { version = "0.12.6", optional = true }
awswrangler = {version = "1.10.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^3.4"
moto = "^1.3"
flake8 = "^3.8.4"
jupyterlab = "^2.2.8"

[tool.poetry.extras]
ge = ["pandas", "great-expectations", "awswrangler"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
data_linter = "data_linter.command_line:main"